export type PaymentStatus = 'pending' | 'processing' | 'approved' | 'declined' | 'timeout' | 'unknown';

export type Currency = 'GHS' | 'NGN' | 'KES' | 'XOF';

export interface PaymentRecord {
  idempotencyKey: string;
  orderId: string;
  customerId: string;
  amount: number;
  currency: string;
  status: PaymentStatus;
  transactionId?: string;
  createdAt: string;
  updatedAt: string;
  retryCount: number;
  autoGeneratedKey: boolean;
  processorMessage?: string;
  processorLatencyMs?: number;
}

export interface DuplicateAttempt {
  idempotencyKey: string;
  attemptTime: string;
  returnedStatus: PaymentStatus;
}

export interface ProcessorResult {
  success: boolean;
  transactionId?: string;
  status: PaymentStatus;
  processorMessage?: string;
  latencyMs: number;
  timedOut: boolean;
}

export interface StoreData {
  payments: Record<string, PaymentRecord>;
  duplicateAttempts: Record<string, DuplicateAttempt[]>;
}
