import { Injectable, Logger } from '@nestjs/common';
import * as crypto from 'crypto';
import { StoreService } from '../store/store.service';
import { DuplicateAttempt, PaymentRecord, PaymentStatus } from '../types/payment.types';

@Injectable()
export class SeedService {
  private readonly logger = new Logger(SeedService.name);

  constructor(private readonly store: StoreService) {}

  private autoKey(
    orderId: string,
    customerId: string,
    amount: number,
    currency: string,
  ): string {
    const payload = `${orderId}:${customerId}:${amount}:${currency}`;
    return crypto
      .createHash('sha256')
      .update(payload)
      .digest('hex')
      .substring(0, 32);
  }

  private rand(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  private pick<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  /** Returns a random date within the last N days */
  private recentDate(withinDays = 7): string {
    const ms = Math.random() * withinDays * 24 * 60 * 60 * 1000;
    return new Date(Date.now() - ms).toISOString();
  }

  async seed(): Promise<{
    message: string;
    paymentsCreated: number;
    duplicatesCreated: number;
    summary: string[];
  }> {
    this.store.clear();

    const currencies: string[] = ['GHS', 'NGN', 'KES', 'XOF'];
    const amountRanges: Record<string, [number, number]> = {
      GHS: [500, 10_000],
      NGN: [5_000, 50_000],
      KES: [1_000, 20_000],
      XOF: [2_000, 30_000],
    };
    const declineReasons = [
      'Insufficient funds',
      'Card declined by issuer',
      'Fraud detection triggered',
      'Card expired',
      'Transaction limit exceeded',
    ];
    const customers = Array.from(
      { length: 20 },
      (_, i) => `cust-${String(i + 1).padStart(4, '0')}`,
    );

    const records: PaymentRecord[] = [];
    const summary: string[] = [];

    // ── 50 standard payments ────────────────────────────────────────────────
    for (let i = 0; i < 50; i++) {
      const currency = this.pick(currencies);
      const [min, max] = amountRanges[currency];
      const amount = this.rand(min, max);
      const customerId = this.pick(customers);
      const orderId = `order-${String(i + 1001).padStart(5, '0')}`;
      const idempotencyKey = this.autoKey(orderId, customerId, amount, currency);

      // Weighted outcome: 70% approved, 20% declined, 10% unknown
      const r = Math.random();
      let status: PaymentStatus;
      let transactionId: string | undefined;
      let processorMessage: string;

      if (r < 0.70) {
        status = 'approved';
        transactionId = `txn-seed-${crypto.randomUUID().split('-')[0]}`;
        processorMessage = 'Payment approved by processor';
      } else if (r < 0.90) {
        status = 'declined';
        processorMessage = this.pick(declineReasons);
      } else {
        status = 'unknown';
        processorMessage = 'Payment processor timed out — actual status unknown';
      }

      const createdAt = this.recentDate(7);
      const record: PaymentRecord = {
        idempotencyKey,
        orderId,
        customerId,
        amount,
        currency,
        status,
        transactionId,
        createdAt,
        updatedAt: createdAt,
        retryCount: 0,
        autoGeneratedKey: true,
        processorMessage,
      };
      records.push(record);
      this.store.setPayment(record);
    }
    summary.push(`50 standard payments (70/20/10 split: approved/declined/unknown)`);

    // ── Edge cases ──────────────────────────────────────────────────────────
    const edgeCases: Array<Partial<PaymentRecord> & { orderId: string; customerId: string }> = [
      {
        orderId: 'order-EDGE-LARGE',
        customerId: 'cust-0001',
        amount: 9_999_999,
        currency: 'NGN',
        status: 'approved',
        transactionId: `txn-edge-large-${crypto.randomUUID().split('-')[0]}`,
        processorMessage: 'High-value payment approved',
      },
      {
        orderId: 'order-EDGE-SMALL',
        customerId: 'cust-0002',
        amount: 1,
        currency: 'GHS',
        status: 'declined',
        processorMessage: 'Transaction amount below minimum threshold',
      },
      {
        orderId: 'order-EDGE-TIMEOUT',
        customerId: 'cust-0003',
        amount: 12_500,
        currency: 'KES',
        status: 'unknown',
        processorMessage: 'Processor timed out — pending confirmation',
      },
    ];

    for (const edge of edgeCases) {
      const currency = edge.currency ?? 'NGN';
      const amount = edge.amount ?? 5_000;
      const idempotencyKey = this.autoKey(
        edge.orderId,
        edge.customerId,
        amount,
        currency,
      );
      const createdAt = this.recentDate(1);
      const record: PaymentRecord = {
        idempotencyKey,
        orderId: edge.orderId,
        customerId: edge.customerId,
        amount,
        currency,
        status: edge.status ?? 'approved',
        transactionId: edge.transactionId,
        createdAt,
        updatedAt: createdAt,
        retryCount: 0,
        autoGeneratedKey: true,
        processorMessage: edge.processorMessage,
      };
      records.push(record);
      this.store.setPayment(record);
    }
    summary.push(
      `3 edge cases: large amount (9,999,999 NGN), minimum amount (1 GHS), pending-timeout (12,500 KES)`,
    );

    // ── 10 duplicate scenarios ──────────────────────────────────────────────
    // Pick the first 13 records and simulate 1-4 retries each
    let duplicatesCreated = 0;
    const duplicateTargets = records.slice(0, 13);

    for (const target of duplicateTargets) {
      const retries = this.rand(1, 4);
      for (let r = 0; r < retries; r++) {
        const delay = (r + 1) * this.rand(5_000, 120_000); // 5s–2m apart
        const attempt: DuplicateAttempt = {
          idempotencyKey: target.idempotencyKey,
          attemptTime: new Date(
            new Date(target.createdAt).getTime() + delay,
          ).toISOString(),
          returnedStatus: target.status,
        };
        this.store.recordDuplicate(target.idempotencyKey, attempt);
        duplicatesCreated++;
      }
      this.store.updatePayment(target.idempotencyKey, { retryCount: retries });
    }
    summary.push(
      `${duplicatesCreated} duplicate attempts across ${duplicateTargets.length} orders (1-4 retries each)`,
    );

    this.logger.log(
      `Seed complete: ${records.length} payments, ${duplicatesCreated} duplicates`,
    );

    return {
      message: 'Test data seeded successfully.',
      paymentsCreated: records.length,
      duplicatesCreated,
      summary,
    };
  }
}
