import { Injectable, Logger } from '@nestjs/common';
import * as crypto from 'crypto';
import { CreatePaymentDto } from './dto/create-payment.dto';
import { StoreService } from '../store/store.service';
import { ProcessorService } from '../processor/processor.service';
import { DuplicateAttempt, PaymentRecord } from '../types/payment.types';

export interface PaymentResponse {
  idempotencyKey: string;
  transactionId?: string;
  status: string;
  amount: number;
  currency: string;
  orderId: string;
  customerId: string;
  processedAt: string;
  /** true when the request was a duplicate — no charge was applied */
  idempotent: boolean;
  message: string;
  /** seconds to wait before retrying a timed-out payment */
  retryAfter?: number;
  processorMessage?: string;
}

@Injectable()
export class PaymentsService {
  private readonly logger = new Logger(PaymentsService.name);

  constructor(
    private readonly store: StoreService,
    private readonly processor: ProcessorService,
  ) {}

  /**
   * Generates a deterministic idempotency key when the client doesn't supply one.
   * Key = SHA-256( orderId:customerId:amount:currency ) truncated to 32 hex chars.
   * This guarantees the same business-level intent always maps to the same key.
   */
  private autoKey(dto: CreatePaymentDto): string {
    const payload = `${dto.orderId}:${dto.customerId}:${dto.amount}:${dto.currency}`;
    return crypto
      .createHash('sha256')
      .update(payload)
      .digest('hex')
      .substring(0, 32);
  }

  async processPayment(
    dto: CreatePaymentDto,
  ): Promise<{ httpStatus: number; body: PaymentResponse }> {
    const autoGenerated = !dto.idempotencyKey;
    const idempotencyKey = dto.idempotencyKey ?? this.autoKey(dto);

    // ── Duplicate check ──────────────────────────────────────────────────────
    const existing = await this.store.getPayment(idempotencyKey);

    if (existing) {
      if (existing.status === 'unknown') {
        // Previous attempt timed out — query processor for a resolution
        return this.resolveTimedOut(existing);
      }

      // Payment already has a final status — return it without charging again
      const dup: DuplicateAttempt = {
        idempotencyKey,
        attemptTime: new Date().toISOString(),
        returnedStatus: existing.status,
      };
      await this.store.recordDuplicate(idempotencyKey, dup);
      await this.store.updatePayment(idempotencyKey, { retryCount: existing.retryCount + 1 });

      this.logger.warn(
        `[Idempotency] Duplicate blocked for key ${idempotencyKey} ` +
        `(order: ${existing.orderId}, status: ${existing.status})`,
      );

      return {
        httpStatus: 200,
        body: {
          idempotencyKey,
          transactionId: existing.transactionId,
          status: existing.status,
          amount: existing.amount,
          currency: existing.currency,
          orderId: existing.orderId,
          customerId: existing.customerId,
          processedAt: existing.createdAt,
          idempotent: true,
          message:
            'Duplicate request detected. Returning cached result — no charge applied.',
          processorMessage: existing.processorMessage,
        },
      };
    }

    // ── New payment ──────────────────────────────────────────────────────────
    // Write "processing" immediately so a concurrent retry sees the record
    // and won't fire off a second processor call (race-condition guard).
    const record: PaymentRecord = {
      idempotencyKey,
      orderId: dto.orderId,
      customerId: dto.customerId,
      amount: dto.amount,
      currency: dto.currency,
      status: 'processing',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      retryCount: 0,
      autoGeneratedKey: autoGenerated,
    };
    await this.store.setPayment(record);

    const result = await this.processor.processPayment(
      dto.amount,
      dto.currency,
      dto.orderId,
    );

    // ── Timeout ──────────────────────────────────────────────────────────────
    if (result.timedOut) {
      await this.store.updatePayment(idempotencyKey, {
        status: 'unknown',
        processorMessage: result.processorMessage,
        processorLatencyMs: result.latencyMs,
      });

      return {
        httpStatus: 202,
        body: {
          idempotencyKey,
          status: 'unknown',
          amount: dto.amount,
          currency: dto.currency,
          orderId: dto.orderId,
          customerId: dto.customerId,
          processedAt: record.createdAt,
          idempotent: false,
          message:
            'Payment processor timed out. Use the same idempotency key to retry — ' +
            'we will check processor status before charging again.',
          retryAfter: 5,
        },
      };
    }

    // ── Final status ─────────────────────────────────────────────────────────
    await this.store.updatePayment(idempotencyKey, {
      status: result.status,
      transactionId: result.transactionId,
      processorMessage: result.processorMessage,
      processorLatencyMs: result.latencyMs,
    });

    return {
      httpStatus: 200,
      body: {
        idempotencyKey,
        transactionId: result.transactionId,
        status: result.status,
        amount: dto.amount,
        currency: dto.currency,
        orderId: dto.orderId,
        customerId: dto.customerId,
        processedAt: record.createdAt,
        idempotent: false,
        message:
          result.status === 'approved'
            ? 'Payment processed successfully.'
            : `Payment ${result.status}: ${result.processorMessage}`,
        processorMessage: result.processorMessage,
      },
    };
  }

  /**
   * Called when a client retries a payment that previously timed out.
   * Queries the processor for the actual outcome before deciding next step.
   */
  private async resolveTimedOut(
    existing: PaymentRecord,
  ): Promise<{ httpStatus: number; body: PaymentResponse }> {
    this.logger.log(
      `[Timeout-Recovery] Querying processor for order ${existing.orderId}`,
    );

    const resolved = await this.processor.queryTransactionStatus(
      existing.orderId,
    );

    if (!resolved) {
      // Processor still can't confirm — ask client to retry again later
      const dup: DuplicateAttempt = {
        idempotencyKey: existing.idempotencyKey,
        attemptTime: new Date().toISOString(),
        returnedStatus: 'unknown',
      };
      await this.store.recordDuplicate(existing.idempotencyKey, dup);

      return {
        httpStatus: 202,
        body: {
          idempotencyKey: existing.idempotencyKey,
          status: 'unknown',
          amount: existing.amount,
          currency: existing.currency,
          orderId: existing.orderId,
          customerId: existing.customerId,
          processedAt: existing.createdAt,
          idempotent: true,
          message:
            'Payment is still being processed. Retry again shortly with the same idempotency key.',
          retryAfter: 10,
        },
      };
    }

    // Resolved — update record and return final status
    await this.store.updatePayment(existing.idempotencyKey, {
      status: resolved.status,
      transactionId: resolved.transactionId,
      processorMessage: resolved.processorMessage,
    });

    const dup: DuplicateAttempt = {
      idempotencyKey: existing.idempotencyKey,
      attemptTime: new Date().toISOString(),
      returnedStatus: resolved.status,
    };
    await this.store.recordDuplicate(existing.idempotencyKey, dup);

    return {
      httpStatus: 200,
      body: {
        idempotencyKey: existing.idempotencyKey,
        transactionId: resolved.transactionId,
        status: resolved.status,
        amount: existing.amount,
        currency: existing.currency,
        orderId: existing.orderId,
        customerId: existing.customerId,
        processedAt: existing.createdAt,
        idempotent: true,
        message: `Timeout resolved — payment ${resolved.status}. No duplicate charge applied.`,
        processorMessage: resolved.processorMessage,
      },
    };
  }

  /**
   * GET /payments/:key — returns current payment status.
   * If status is still "unknown", attempts a live processor status query first.
   */
  async getPaymentStatus(idempotencyKey: string): Promise<PaymentRecord | null> {
    const record = await this.store.getPayment(idempotencyKey);
    if (!record) return null;

    if (record.status === 'unknown') {
      const resolved = await this.processor.queryTransactionStatus(
        record.orderId,
      );
      if (resolved) {
        return (
          (await this.store.updatePayment(idempotencyKey, {
            status: resolved.status,
            transactionId: resolved.transactionId,
            processorMessage: resolved.processorMessage,
          })) ?? record
        );
      }
    }

    return record;
  }

  async getAllPayments(): Promise<PaymentRecord[]> {
    return this.store.getAllPayments();
  }
}
